In [1]:
pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-0.3.6-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: packaging in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: requests in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from requests->kagglehub) (2024.12.14)
Requirement already satisfied: colorama in c:\users\user\anaconda3\envs\machinelearning\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-0.3.6-py3-none-any.whl (51 kB)
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import cv2
import kagglehub
import os

C:\Users\user\anaconda3\envs\MachineLearning\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
path = kagglehub.dataset_download("rahmasleam/flowers-dataset")

Downloading from https://www.kaggle.com/api/v1/datasets/download/rahmasleam/flowers-dataset?dataset_version_number=1...

100%|███████████████████████████████████████████████████████████████████████████████| 219M/219M [00:22<00:00, 10.4MB/s]

Extracting files...

In [4]:

path

'C:\\Users\\user\\.cache\\kagglehub\\datasets\\rahmasleam\\flowers-dataset\\versions\\1'

In [5]:
 # prints the contents in that folder
folders = os.listdir(r"C:\Users\user\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos")
folders

['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']

In [6]:
features = []
class_labels = []
for folder in folders:
    for images in os.listdir(r"C:\Users\user\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\{}".format(folder)):
        img = cv2.imread(r"C:\Users\user\.cache\kagglehub\datasets\rahmasleam\flowers-dataset\versions\1\flower_photos\{}\{}".format(folder, images), 0) # Array representation # 0 --> Grayscale, 1 --> RGB image
        img = cv2.resize(img, (50,50)) # resizing the image
        img = img.flatten() # flattening the image
        features.append(img) # Appending each flattened image to list
        class_labels.append(folder) # Appending each class label to list

In [7]:
final_data = pd.DataFrame(features)
final_data

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
0,143,149,160,169,167,167,145,144,144,159,...,171,174,168,149,134,128,137,137,131,127
1,224,222,216,232,228,75,85,80,182,185,...,120,116,107,110,108,156,169,141,125,172
2,108,81,97,84,102,120,108,106,140,128,...,38,44,27,26,26,27,27,31,36,40
3,26,25,26,29,32,35,37,38,38,40,...,18,16,15,16,21,18,24,16,20,23
4,20,21,36,45,46,45,40,42,37,56,...,26,42,48,42,26,25,31,39,27,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3665,212,189,186,212,47,82,116,131,82,79,...,83,103,114,40,7,30,30,86,194,215
3666,135,126,129,131,119,141,135,128,132,136,...,48,53,60,58,54,41,48,84,132,120
3667,88,72,78,97,57,77,91,79,46,77,...,83,71,81,89,91,91,87,103,80,80
3668,157,189,169,132,174,162,185,174,122,160,...,57,152,193,74,23,18,8,12,19,45
3669,49,62,118,122,75,164,127,98,74,78,...,98,146,80,45,63,47,91,56,76,57

In [8]:
final_data["Class Labels"] = class_labels
final_data

,0,1,2,3,4,5,6,7,8,9,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,Class Labels
0,143,149,160,169,167,167,145,144,144,159,...,174,168,149,134,128,137,137,131,127,daisy
1,224,222,216,232,228,75,85,80,182,185,...,116,107,110,108,156,169,141,125,172,daisy
2,108,81,97,84,102,120,108,106,140,128,...,44,27,26,26,27,27,31,36,40,daisy
3,26,25,26,29,32,35,37,38,38,40,...,16,15,16,21,18,24,16,20,23,daisy
4,20,21,36,45,46,45,40,42,37,56,...,42,48,42,26,25,31,39,27,35,daisy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3665,212,189,186,212,47,82,116,131,82,79,...,103,114,40,7,30,30,86,194,215,tulips
3666,135,126,129,131,119,141,135,128,132,136,...,53,60,58,54,41,48,84,132,120,tulips
3667,88,72,78,97,57,77,91,79,46,77,...,71,81,89,91,91,87,103,80,80,tulips
3668,157,189,169,132,174,162,185,174,122,160,...,152,193,74,23,18,8,12,19,45,tulips
3669,49,62,118,122,75,164,127,98,74,78,...,146,80,45,63,47,91,56,76,57,tulips

In [9]:
final_data.info() # if dtype is uint8, no need to convert. If its int8 we need to convert it using final_data.astype(np.unit8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3670 entries, 0 to 3669
Columns: 2501 entries, 0 to Class Labels
dtypes: object(1), uint8(2500)
memory usage: 8.8+ MB